### ISSUE TITLE
Demo Link not working

### ISSUE THREAD

**Issue by vipulasri** [mohitmamoria/blame-praise#6]
http://mohitmamoria.com/fun/blame-praise link not working :/
![screenshot 2](https://cloud.githubusercontent.com/assets/7822179/10459516/79bcdf44-71ed-11e5-9e4c-8b24e1d8a195.png)

**Comment by mohitmamoria** [comment]
@vipulasri Oh yes.. It doesn't work now. Have shut it down. Looks like I forgot to remove the link. :/
